# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b03f247481319abd1b8b6f2c26810a440545252bb17d274f2fcabfed370da26b76b17758e47cdb3a446b1eb19e4d9ff0f94711811672b8182bde40eb1ca8fe58

test:
  secret_key_base: 238b89f5b9597dab7341cefe64a3aeb41a36b5987c7bd0d7f5512a6047088c534d3ff7724b73a1d4861dd7c4edd8753fe9755933c76c939cde87f0719768b8b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
